export const LOADING="LOADING"

export const REGISTERSUCCSESS="REGISTERSUCCSESS"


export const LOGINSUCCSESS="LOGINSUCCSESS"

export const CURRENTUSERAUTH="CURRENTUSERAUTH"

export const LOGOUT="LOGOUT"

export const AUTHFAILED="AUTHFAILED"

