export const LOADING = "LOADING";
export const FAILD = "FAILD";

export const GETALLPRODCUTSSUCCESS = "GETALLPRODCUTSSUCCESS";
export const GETONEPRODCUTSSUCCESS = "GETONEPRODCUTSSUCCESS";

export const ADDPRODUCT = "ADDPRODUCT";

export const EDITPRODUCT = "EDITPRODUCT";

export const DELETEPRODUCT = "DELETEPRODUCT";