export const RLOADING = "RLOADING";
export const RFAILD = "RFAILD";

export const GETPRODUCTREVIEWSSUCCESS = "GETPRODUCTREVIEWSSUCCESS";
export const ADDREVIEWSSUCCESS = "ADDREVIEWSSUCCESS";

export const DELETEREVIEW = "DELETEREVIEW";

export const EDITREVIEW = "EDITREVIEW";